apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring

data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "cloud-job-api"

        static_configs:
          - targets: ["api-service.cloud-job-system.svc.cluster.local:3000"]