apiVersion: v1
kind: Secret
metadata:
  name: cloud-job-secret
  namespace: cloud-job-system
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/cloud_job_system?schema=public"