name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build API
        run: npm run build

  build-worker:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: worker-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build Worker
        run: npm run build